version: "3.9"
services:
  server:
    container_name: server
    build: .
    volumes:
      - '.:/app:rw'
      - '/app/node_modules'
    environment:
      REDIS_URI: redis://redis:6379
    links:
      - redis
    ports:
      - "5000:5000"
  
  redis:
    image: "redis:alpine"
    

    