version: '3.9'

services:
  web:
    container_name: web
    build: .
    ports: 
      - "3000"
  nginx-proxy:
    container_name: nginx-proxy
    build: nginx/
    ports:
      - "80:80"
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock